In [23]:
print("1.Import numpy as np")

1.Import numpy as np


In [6]:
import numpy as np

In [24]:
print("2.Create 10 zeroes")

2.Create 10 zeroes


In [2]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [25]:
print("3.Create a vector with values ranging from 10 to 100")

3.Create a vector with values ranging from 10 to 100


In [157]:
X = np.arange(10,100)
print("Original array:")
print(X)


Original array:
[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53 54 55 56 57
 58 59 60 61 62 63 64 65 66 67 68 69 70 71 72 73 74 75 76 77 78 79 80 81
 82 83 84 85 86 87 88 89 90 91 92 93 94 95 96 97 98 99]


In [26]:
print("4.Reverse it")

4.Reverse it


In [53]:

print("Reverse array:")
X= X[::-1]
print(X)



Reverse array:
[99 98 97 96 95 94 93 92 91 90 89 88 87 86 85 84 83 82 81 80 79 78 77 76
 75 74 73 72 71 70 69 68 67 66 65 64 63 62 61 60 59 58 57 56 55 54 53 52
 51 50 49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28
 27 26 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


In [52]:
print("5.Reshape it to a 3x30")

5.Reshape it to a 3x30


In [58]:
Y_reshaped = Y.reshape(3,30)
print(Y_reshaped)

[[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
  34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63
  64 65 66 67 68 69]
 [70 71 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93
  94 95 96 97 98 99]]


In [59]:
print("6.Create the vector with elems 1,2,9,0,0,1,4,0. Find indices of non-zero elems")

6.Create the vector with elems 1,2,9,0,0,1,4,0. Find indices of non-zero elems


In [61]:
X=[1,2,9,0,0,1,4,0]
X

[1, 2, 9, 0, 0, 1, 4, 0]

In [62]:
np.nonzero(X)

(array([0, 1, 2, 5, 6], dtype=int64),)

In [63]:
print("7.Create a 3x3 identity matrix")

7.Create a 3x3 identity matrix


In [13]:
print("The identity matrix:")
I=np.eye(3,dtype=int)
print(I)


The identity matrix:
[[1 0 0]
 [0 1 0]
 [0 0 1]]


In [11]:
print("8.Create a random vector of size 50 with values uniformely distributed in (-1, 1). Find the average of these values.")

8.Create a random vector of size 50 with values uniformely distributed in (-1, 1). Find the average of these values.


In [17]:
Z=np.random.uniform(-1,1,50)
print(Z)

[ 0.18106812  0.04703321  0.01227781 -0.58487186  0.90650837  0.02991835
 -0.58926328  0.28967059 -0.11881492  0.06983226 -0.82598901  0.2758421
 -0.13779061  0.75849172 -0.87439861 -0.19122093 -0.69879304 -0.69027209
 -0.01804043 -0.73982433 -0.08175448  0.05084432 -0.94069604  0.37017548
  0.97107353  0.38132776 -0.04961565  0.81881462 -0.39473851  0.16193199
  0.65613541  0.76994619  0.5213599   0.91992933  0.31136025  0.60781815
 -0.42735884 -0.4536837   0.7539748  -0.76614696 -0.03798056 -0.49232586
 -0.41703925  0.63813866  0.18550107 -0.63946696 -0.63807593  0.02448429
  0.36159089  0.6277961 ]


In [20]:
np.average(Z)

0.017893667907193732

In [21]:
np.mean(Z)

0.017893667907193732

In [23]:
print("9.Create a 5x5 matrix with 1,2,3,4 just below the 1st diag and 0 in rest.")

9.Create a 5x5 matrix with 1,2,3,4 just below the 1st diag and 0 in rest.


In [27]:
W = np.diag(1+np.arange(4),k=-1)
print(W)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


In [28]:
print("10.Create a 5x3 matrix and a 3x4 one. Multiply them. ")

10.Create a 5x3 matrix and a 3x4 one. Multiply them. 


In [47]:
A=np.matrix('1.1 2 3.3; 4 5 6.5; 7 8 9.2; 10 11.4 12; 13.1 14 15')
print(A)

[[ 1.1  2.   3.3]
 [ 4.   5.   6.5]
 [ 7.   8.   9.2]
 [10.  11.4 12. ]
 [13.1 14.  15. ]]


In [92]:
B=np.matrix('1.9 2 3.4 4; 5 6 7.5 8; 9 10.5 11 12')
print(B)

[[ 1.9  2.   3.4  4. ]
 [ 5.   6.   7.5  8. ]
 [ 9.  10.5 11.  12. ]]


In [48]:
K = np.dot(A,B)
print(K)

[[ 41.79  48.85  55.04  60.  ]
 [ 91.1  106.25 122.6  134.  ]
 [136.1  158.6  185.   202.4 ]
 [184.   214.4  251.5  275.2 ]
 [229.89 267.7  314.54 344.4 ]]


In [41]:
print('11.Using the previous matrix, extract a new one with just the integer part of the values. Find at least 4 methods of doing this.')

11.Using the previous matrix, extract a new one with just the integer part of the values. Find at least 4 methods of doing this.


In [50]:
print('PRIMA METODA:')
print (K - K%1)


PRIMA METODA:
[[ 41.  48.  55.  60.]
 [ 91. 106. 122. 134.]
 [136. 158. 185. 202.]
 [184. 214. 251. 275.]
 [229. 267. 314. 344.]]


In [54]:
print('A 2-a METODA:')
print (np.trunc(K))

A 2-a METODA:
[[ 41.  48.  55.  60.]
 [ 91. 106. 122. 134.]
 [136. 158. 185. 202.]
 [184. 214. 251. 275.]
 [229. 267. 314. 344.]]


In [55]:
print('A 3-a METODA:')
print (K.astype(int))

A 3-a METODA:
[[ 41  48  55  60]
 [ 91 106 122 134]
 [136 158 185 202]
 [184 214 251 275]
 [229 267 314 344]]


In [56]:
print('A 4-a METODA:')
print (np.floor(K))

A 4-a METODA:
[[ 41.  48.  55.  60.]
 [ 91. 106. 122. 134.]
 [136. 158. 185. 202.]
 [184. 214. 251. 275.]
 [229. 267. 314. 344.]]


In [58]:
print('12.Create a random vector of size 25. Sort it.')

12.Create a random vector of size 25. Sort it.


In [62]:
L = np.random.random(25)
print(L)

[0.59246696 0.20943225 0.34624479 0.86238714 0.33913555 0.47180423
 0.525201   0.76652057 0.63652326 0.98445181 0.1914803  0.70599917
 0.01007249 0.70000951 0.19243046 0.39149526 0.75219706 0.52300188
 0.87005486 0.29931065 0.04334792 0.15711319 0.62211123 0.54298772
 0.68786158]


In [64]:
L.sort()
print(L)

[0.01007249 0.04334792 0.15711319 0.1914803  0.19243046 0.20943225
 0.29931065 0.33913555 0.34624479 0.39149526 0.47180423 0.52300188
 0.525201   0.54298772 0.59246696 0.62211123 0.63652326 0.68786158
 0.70000951 0.70599917 0.75219706 0.76652057 0.86238714 0.87005486
 0.98445181]


In [65]:
print('13.Create a random 7x2 matrix representing 7 2D points. Convert them to polar coordinates.')

13.Create a random 7x2 matrix representing 7 2D points. Convert them to polar coordinates.


In [67]:
A = np.random.random((7,2))
print(A)

[[0.55985493 0.89127581]
 [0.13795388 0.92239656]
 [0.42583596 0.01678234]
 [0.76985378 0.56302628]
 [0.07262223 0.58927588]
 [0.211745   0.80366482]
 [0.96861751 0.80760816]]


In [163]:
x,y = A[:,0], A[:,1]
r = np.sqrt(x**2+y**2)
teta = np.arctan2(y,x)
print('Coordonata polara "r":')
print(r)
print('Coordonata polara "teta":')
print(teta)

Coordonata polara "r":
[92.4175308  81.60882305 66.37017402 43.18564576 84.52810184 60.41522987
 90.42676595]
Coordonata polara "teta":
[0.62402305 1.2722974  1.46513074 1.47804001 1.11773033 1.14416883
 1.39292106]


In [70]:
print('14.Generate a 10x10 matrix. Generate a single random number. Find the number in the matrix closest to it.')

14.Generate a 10x10 matrix. Generate a single random number. Find the number in the matrix closest to it.


In [147]:
M=np.random.randint(0,100,(10,10)) 
print(M)

[[22 26 33 82 19  6 35 39 30 78]
 [23  0 28 11 17  2 97 85 58 81]
 [24 25 84 25 17 42 37 56 67 93]
 [60 24 50  7 63 59 49 19 16 96]
 [41 79 78 93  3 33 17 11  0 76]
 [56 16 34 37  8  9 43 51 44 45]
 [45 78 90 48 53 50 96 11 60 21]
 [15 12 93 38 68 65 56 13 99  8]
 [71 82 39 17 47 95 63 24 20 24]
 [52 84 25 43 68 82 95 33 67 40]]


In [154]:
nr=np.random.randint(0,100)
print(nr)

31


In [155]:
ValCautata = (np.abs(M.flatten()-nr)).argmin()
print('Valoarea cea mai apropiata de "nr" este:')
print(M.flatten()[ValCautata])

Valoarea cea mai apropiata de "nr" este:
30
